
#include <cppbuild.hpp>

int main(int argc, char* argv[])
{
    cppbuild::init(argc, argv);
    
    cppbuild::Target target("editor");

    target.folder(cppbuild::Folder("src")
            .files({
                "program.cpp",
            })
        );
        
    target.folder(cppbuild::Folder("libs")
            .folder(cppbuild::Folder("scintilla")
                .folder(cppbuild::Folder("src")
                    .files({
                        "AutoComplete.cxx",
                        "CallTip.cxx",
                        "CaseConvert.cxx",
                        "CaseFolder.cxx",
                        "Catalogue.cxx",
                        "CellBuffer.cxx",
                        "CharClassify.cxx",
                        "ContractionState.cxx",
                        "Decoration.cxx",
                        "Document.cxx",
                        "EditModel.cxx",
                        "Editor.cxx",
                        "EditView.cxx",
                        "ExternalLexer.cxx",
                        "Indicator.cxx",
                        "KeyMap.cxx",
                        "LineMarker.cxx",
                        "MarginView.cxx",
                        "PerLine.cxx",
                        "PositionCache.cxx",
                        "RESearch.cxx",
                        "RunStyles.cxx",
                        "ScintillaBase.cxx",
                        "Selection.cxx",
                        "Style.cxx",
                        "UniConversion.cxx",
                        "ViewStyle.cxx",
                        "XPM.cxx",
                    })
                )
                .folder(cppbuild::Folder("lexlib")
                    .files({
                        "Accessor.cxx",
                        "CharacterCategory.cxx",
                        "CharacterSet.cxx",
                        "LexerBase.cxx",
                        "LexerModule.cxx",
                        "LexerNoExceptions.cxx",
                        "LexerSimple.cxx",
                        "PropSetSimple.cxx",
                        "WordList.cxx",
                        "StyleContext.cxx",
                    })
                )
                .folder(cppbuild::Folder("win32")
                    .files({
                        "PlatWin.cxx",
                        "HanjaDic.cxx",
                        "ScintillaWin.cxx",
                    })
                )
                .folder(cppbuild::Folder("lexers")
                    .files({
                        "LexA68k.cxx",
                        "LexAbaqus.cxx",
                        "LexAda.cxx",
                        "LexAPDL.cxx",
                        "LexAsm.cxx",
                        "LexAsn1.cxx",
                        "LexASY.cxx",
                        "LexAU3.cxx",
                        "LexAVE.cxx",
                        "LexAVS.cxx",
                        "LexBaan.cxx",
                        "LexBash.cxx",
                        "LexBasic.cxx",
                        "LexBatch.cxx",
                        "LexBibTeX.cxx",
                        "LexBullant.cxx",
                        "LexCaml.cxx",
                        "LexCLW.cxx",
                        "LexCmake.cxx",
                        "LexCOBOL.cxx",
                        "LexCoffeeScript.cxx",
                        "LexConf.cxx",
                        "LexCPP.cxx",
                        "LexCrontab.cxx",
                        "LexCsound.cxx",
                        "LexCSS.cxx",
                        "LexD.cxx",
                        "LexDiff.cxx",
                        "LexDMAP.cxx",
                        "LexDMIS.cxx",
                        "LexECL.cxx",
                        "LexEDIFACT.cxx",
                        "LexEiffel.cxx",
                        "LexErlang.cxx",
                        "LexErrorList.cxx",
                        "LexEScript.cxx",
                        "LexFlagship.cxx",
                        "LexForth.cxx",
                        "LexFortran.cxx",
                        "LexGAP.cxx",
                        "LexGui4Cli.cxx",
                        "LexHaskell.cxx",
                        "LexHex.cxx",
                        "LexHTML.cxx",
                        "LexInno.cxx",
                        "LexJSON.cxx",
                        "LexKix.cxx",
                        "LexKVIrc.cxx",
                        "LexLaTeX.cxx",
                        "LexLisp.cxx",
                        "LexLout.cxx",
                        "LexLua.cxx",
                        "LexMagik.cxx",
                        "LexMake.cxx",
                        "LexMarkdown.cxx",
                        "LexMatlab.cxx",
                        "LexMetapost.cxx",
                        "LexMMIXAL.cxx",
                        "LexModula.cxx",
                        "LexMPT.cxx",
                        "LexMSSQL.cxx",
                        "LexMySQL.cxx",
                        "LexNimrod.cxx",
                        "LexNsis.cxx",
                        "LexNull.cxx",
                        "LexOpal.cxx",
                        "LexOScript.cxx",
                        "LexPascal.cxx",
                        "LexPB.cxx",
                        "LexPerl.cxx",
                        "LexPLM.cxx",
                        "LexPO.cxx",
                        "LexPOV.cxx",
                        "LexPowerPro.cxx",
                        "LexPowerShell.cxx",
                        "LexProgress.cxx",
                        "LexProps.cxx",
                        "LexPS.cxx",
                        "LexPython.cxx",
                        "LexR.cxx",
                        "LexRebol.cxx",
                        "LexRegistry.cxx",
                        "LexRuby.cxx",
                        "LexRust.cxx",
                        "LexScriptol.cxx",
                        "LexSmalltalk.cxx",
                        "LexSML.cxx",
                        "LexSorcus.cxx",
                        "LexSpecman.cxx",
                        "LexSpice.cxx",
                        "LexSQL.cxx",
                        "LexSTTXT.cxx",
                        "LexTACL.cxx",
                        "LexTADS3.cxx",
                        "LexTAL.cxx",
                        "LexTCL.cxx",
                        "LexTCMD.cxx",
                        "LexTeX.cxx",
                        "LexTxt2tags.cxx",
                        "LexVB.cxx",
                        "LexVerilog.cxx",
                        "LexVHDL.cxx",
                        "LexVisualProlog.cxx",
                        "LexYAML.cxx",
                    })
                )
            )
        );
    target.includeDirs({
        "libs\\scintilla\\include",
        "libs\\scintilla\\src",
        "libs\\scintilla\\lexlib",
    });

    target.libraries({
        "kernel32",
        "user32",
        "gdi32",
        "ole32",
        "oleaut32",
        "imm32",
        "uuid",
    });
    
    target.compilerFlags({ "-D_UNICODE", "-DUNICODE" });

    return 0;
}